### ISSUE TITLE
Compliments 

### ISSUE THREAD

**Issue by kinsleykajiva** [flutterjanus/JanusJs#2]
Hi , i have to say well done this looks good and i am yet to test this as much . the effort if much appreciated as much ey .
Do you have a java Android or the  javafx version of the implementation ?

**Comment by shivanshtalwar0** [comment]
Thanks for the compliments, i still want to add lot of helper methods and features so that this can be goto javascript client, regarding java client at the moment nothing of that sort i have worked on but you will be able to find some good projects out there
